### ISSUE TITLE
arrow-list fails to build with ghc-8.8: src/Control/Monad/Sequence.hs:57:3: error:  ‘fail’ is not a (visible) method of class ‘Monad’

### ISSUE THREAD

**Issue by trofi** [silkapp/arrow-list#2]
Noticed when tried to build current git version:
```
[5 of 6] Compiling Control.Monad.Sequence ( src/Control/Monad/Sequence.hs, dist/build/Control/Monad/Sequence.o )

src/Control/Monad/Sequence.hs:57:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
57 |   fail _ = SeqT (return mempty)
   |   ^^^^
```

**Comment by hesselink** [comment]
Fixed in 0.7.1.
